import ActivationKit
import AppKit
import MacAutomation
import SceneCore
import SwiftUI

struct RunHistoryView: View {
    @ObservedObject var model: AppModel
    @State private var query = ""
    @State private var selectedStatus: SceneRunStatus?
    @State private var confirmsClear = false
    private var runs: [SceneRunResult] { model.runHistory.filter { (query.isEmpty || $0.sceneName.localizedCaseInsensitiveContains(query)) && (selectedStatus == nil || $0.status == selectedStatus) } }
    var body: some View { VStack(alignment: .leading, spacing: 16) { HStack { Text("Run History").font(.largeTitle.bold()); Spacer(); Button("Clear History", role: .destructive) { confirmsClear = true }.disabled(model.runHistory.isEmpty) }; HStack { TextField("Search scenes", text: $query).textFieldStyle(.roundedBorder); Picker("Status", selection: $selectedStatus) { Text("All statuses").tag(SceneRunStatus?.none); ForEach(SceneRunStatus.allCases, id: \.self) { Text($0.displayName).tag(Optional($0)) } }.frame(width: 210) }; if runs.isEmpty { ContentUnavailableView("No Matching Runs", systemImage: "clock.arrow.circlepath", description: Text("Completed runs appear here with bounded redacted details.")) } else { List(runs) { run in HStack { WorkspaceCoreView(status: run.status, progress: run.actionRecords.isEmpty ? 0 : Double(run.completedActionCount) / Double(run.actionRecords.count), compact: true); VStack(alignment: .leading, spacing: 4) { Text(run.sceneName).font(.headline); Text(run.startedAt?.formatted() ?? "Unknown start").font(.caption).foregroundStyle(ObsidianTokens.mutedText); Text("\(run.completedActionCount) actions • \(run.warningCount) warnings • \(run.failureCount) failures").font(.caption.monospaced()) }; Spacer(); StatusBadge(text: run.status.displayName, color: run.status.color, symbol: run.status.symbol) }.padding(.vertical, 6).listRowBackground(ObsidianTokens.panel).contextMenu { Button("Delete Run", role: .destructive) { Task { await model.deleteRun(run) } } } }.scrollContentBackground(.hidden) } }.padding(28).accessibilityIdentifier("screen.history").confirmationDialog("Clear all run history?", isPresented: $confirmsClear, titleVisibility: .visible) { Button("Clear History", role: .destructive) { Task { await model.clearRunHistory() } } } message: { Text("This removes local run records. Scene definitions are not affected.") } }
}

struct IntegrationsView: View {
    @ObservedObject var model: AppModel
    var body: some View { VStack(alignment: .leading, spacing: 16) { Text("Integrations").font(.largeTitle.bold()); Text("Detected locally—no inventory leaves this Mac.").foregroundStyle(ObsidianTokens.secondaryText); List(model.integrations) { integration in HStack { Image(systemName: integration.installed ? "checkmark.circle.fill" : "circle.dashed").foregroundStyle(integration.installed ? ObsidianTokens.success : ObsidianTokens.mutedText); VStack(alignment: .leading, spacing: 3) { Text(integration.displayName).font(.headline); Text(integration.path ?? "Not found in a supported location").font(.caption.monospaced()).foregroundStyle(ObsidianTokens.secondaryText); Text(integration.privacyNote).font(.caption).foregroundStyle(ObsidianTokens.mutedText) }; Spacer(); if let version = integration.version { Text(version).font(.caption.monospaced()) }; StatusBadge(text: integration.installed ? "Installed" : "Missing", color: integration.installed ? ObsidianTokens.success : ObsidianTokens.warning, symbol: integration.installed ? "checkmark" : "questionmark") }.padding(.vertical, 7).listRowBackground(ObsidianTokens.panel) }.scrollContentBackground(.hidden) }.padding(28).accessibilityIdentifier("screen.integrations") }
}

struct PermissionsView: View {
    @ObservedObject var model: AppModel
    var body: some View { VStack(alignment: .leading, spacing: 18) { Text("Permissions").font(.largeTitle.bold()); Text("Optional capabilities ask only when you enable or use them.").foregroundStyle(ObsidianTokens.secondaryText); PermissionRow(title: "Accessibility", detail: "Reviewed window capture and layout restoration only", state: model.accessibilityPermission.status(), request: { _ = model.accessibilityPermission.requestExplicitly() }, settings: { Task { await model.accessibilityPermission.openSystemSettings() } }); PermissionRow(title: "Microphone", detail: "Opt-in local clap detection and explicit voice command sessions", state: permissionState(model.microphonePermissionStatus), request: { Task { await model.setClapEnabled(true) } }, settings: { openPrivacySettings("Privacy_Microphone") }); PermissionRow(title: "Speech Recognition", detail: "On-device voice recognition only; no cloud fallback", state: permissionState(model.speechPermissionStatus), request: { Task { await model.beginVoiceCommand() } }, settings: { openPrivacySettings("Privacy_SpeechRecognition") }); PermissionRow(title: "Notifications", detail: "Optional ready, warning, and failure notifications", state: model.notificationPermissionStatus, request: { Task { await model.setNotificationsEnabled(true) } }, settings: { openPrivacySettings("Notifications") }); Spacer() }.padding(28).accessibilityIdentifier("screen.permissions") }
    private func permissionState(_ state: ActivationPermissionStatus) -> PermissionState { switch state { case .notDetermined: .notDetermined; case .denied: .denied; case .granted: .granted; case .restricted: .unavailable } }
    private func openPrivacySettings(_ pane: String) { if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?\(pane)") { NSWorkspace.shared.open(url) } }
}
private struct PermissionRow: View { let title: String; let detail: String; let state: PermissionState; let request: (() -> Void)?; let settings: (() -> Void)?; var body: some View { HStack { Image(systemName: state == .granted ? "checkmark.shield.fill" : "shield.lefthalf.filled").font(.title2).foregroundStyle(state == .granted ? ObsidianTokens.success : ObsidianTokens.warning); VStack(alignment: .leading) { Text(title).font(.headline); Text(detail).foregroundStyle(ObsidianTokens.secondaryText) }; Spacer(); Text(state.rawValue.capitalized).font(.caption.monospaced()); if let request { Button("Request", action: request) }; if let settings { Button("Settings", action: settings) } }.obsidianPanel() } }

struct DiagnosticsView: View {
    @ObservedObject var model: AppModel
    @State private var copied = false
    var body: some View { ScrollView { VStack(alignment: .leading, spacing: 16) { HStack { Text("Diagnostics").font(.largeTitle.bold()); Spacer(); Button(copied ? "Copied" : "Copy Summary") { model.copyDiagnostics(); copied = true }.accessibilityHint("Copies a bounded summary without scene content or process output") }; Group { LabeledContent("App version", value: model.appVersion); LabeledContent("Build", value: model.buildNumber); LabeledContent("macOS", value: ProcessInfo.processInfo.operatingSystemVersionString); LabeledContent("Architecture", value: architecture); LabeledContent("Scenes", value: "\(model.scenes.count)"); LabeledContent("Run history", value: "\(model.runHistory.count)"); LabeledContent("Accessibility", value: model.accessibilityPermission.status().rawValue); LabeledContent("Microphone", value: model.microphonePermissionStatus.rawValue); LabeledContent("Speech", value: model.speechPermissionStatus.rawValue); LabeledContent("Notifications", value: model.notificationPermissionStatus.rawValue); LabeledContent("Launch at login", value: model.launchAtLoginStatus.rawValue); LabeledContent("Scene storage", value: "~/Library/Application Support/WorkspaceOrchestrator/scenes.json"); LabeledContent("Run history storage", value: "~/Library/Application Support/WorkspaceOrchestrator/RunHistory") }.obsidianPanel(); HStack { Button("Refresh Self-Check") { Task { await model.refresh() } }; Text("Self-check reports actual discovery and permission state; it does not contact a support service.").foregroundStyle(ObsidianTokens.secondaryText) }; Text("Copied diagnostics omit scene definitions and output. Other diagnostic exports may still contain private data; review before sharing.").font(.callout).foregroundStyle(ObsidianTokens.warning) }.padding(28) }.accessibilityIdentifier("screen.diagnostics") }
    private var architecture: String {
        #if arch(arm64)
        return "arm64"
        #elseif arch(x86_64)
        return "x86_64"
        #else
        return "unknown"
        #endif
    }
}

struct WorkspaceCaptureView: View {
    @ObservedObject var model: AppModel
    @State private var selectedBundleIDs = Set<String>()
    @State private var name = "Captured Workspace"
    @State private var manualURLs = ""
    private var urls: [String] { manualURLs.split(whereSeparator: \.isNewline).map(String.init) }
    var body: some View { VStack(alignment: .leading, spacing: 16) { Text("Capture Current Workspace").font(.largeTitle.bold()); Text("Select applications and optionally add reviewed URLs. Window details require Accessibility. Browser/terminal history, clipboard, document contents, environment variables, Docker projects, and secrets are never inferred.").foregroundStyle(ObsidianTokens.secondaryText); HStack { TextField("Scene name", text: $name).textFieldStyle(.roundedBorder); TextField("HTTP(S) URLs, one per line", text: $manualURLs, axis: .vertical).lineLimit(1...3).textFieldStyle(.roundedBorder) }; List(model.capturableApplications) { item in Toggle(isOn: Binding(get: { selectedBundleIDs.contains(item.id) }, set: { if $0 { selectedBundleIDs.insert(item.id) } else { selectedBundleIDs.remove(item.id) }; model.selectCaptureApplications(selectedBundleIDs) })) { VStack(alignment: .leading) { Text(item.displayName); Text(item.id).font(.caption.monospaced()).foregroundStyle(ObsidianTokens.mutedText) } }.listRowBackground(ObsidianTokens.panel) }.scrollContentBackground(.hidden); HStack { Button("Refresh Applications") { model.refreshCapturableApplications() }; Button("Review Window Capture") { Task { await model.capture(bundleIdentifiers: selectedBundleIDs) } }.disabled(selectedBundleIDs.isEmpty); Text("\(selectedBundleIDs.count) apps • \(model.capturedWindows.count) reviewed windows • \(urls.count) URLs").foregroundStyle(ObsidianTokens.secondaryText); Spacer(); Button("Save Reviewed Scene") { model.selectCaptureApplications(selectedBundleIDs); Task { await model.sceneFromCapture(name: name, manualURLs: urls) } }.buttonStyle(.borderedProminent).disabled(selectedBundleIDs.isEmpty && urls.isEmpty) } }.padding(28).task { model.refreshCapturableApplications() } }
}
